version: "2.2"
services:
  postgres:
    build: postgres
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_DB: '${PG_DATABASE}'
    env_file: '.env'
    ports:
      - 5432:5432
    volumes:
      # https://github.com/docker-library/postgres/issues/116
      - ./data/pg:/var/lib/postgresql/data:z
    healthcheck:
      test: 'pg_isready -U postgres'
      interval: 5s
      timeout: 10s
      retries: 12
  graphql:
    build: server
    volumes:
      - './server/migrations:/app/migrations'
      - './server/src:/app/src'
      - './server/package.json:/app/package.json'
    init: true
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    env_file: '.env'
    environment:
      PG_HOST: '${PG_HOST}'
      PG_PORT: 5432
      DB_SCHEMA: '${DB_SCHEMA}'
      PG_USER: '${PG_USER}'
      PG_PASSWORD: '${PG_PASSWORD}'
      PG_DATABASE: '${PG_DATABASE}'
      PG_DEFAULT_ROLE: '${PG_DEFAULT_ROLE}'
